import { CelestialBody } from '@/types/universe';

export const PLANETS_CONFIG: CelestialBody[] = [
  {
    id: 'central',
    name: 'RAGHAV',
    subtitle: 'Central Identity Core',
    tagline: 'Mathematics & Computing — Delhi, India',
    orbitalRadius: 0,
    orbitalSpeed: 0.05,
    orbitalInclination: 0,
    size: 2.2,
    baseColor: '#ffffff',
    glowColor: '#fef08a',
    atmosphereColor: '#ca8a04',
    initialAngle: 0,
    position: [0, 0, 0],
    composition: {
      cameraPositionOffset: [-2.8, 0.45, 6.8],
      lookAtOffset: [1.0, 0, 0],
      fov: 45,
      contentAnchor: 'right',
      safeUiWidthPercent: 46,
      planetScreenPosition: 'left-center',
    },
  },
  {
    id: 'code',
    name: 'CODE',
    subtitle: 'Competitive Programming & DSA',
    tagline: 'Algorithmic Problem Solving, Contest Rigor & Discrete Structures',
    orbitalRadius: 11,
    orbitalSpeed: 0.25,
    orbitalInclination: 0.08,
    size: 1.15,
    baseColor: '#0c4a6e',
    glowColor: '#00f0ff',
    atmosphereColor: '#0284c7',
    initialAngle: 0.4,
    position: [10.2, 1.1, 4.1],
    wireframe: true,
    composition: {
      cameraPositionOffset: [-2.4, 0.35, 3.6],
      lookAtOffset: [0.75, 0, 0],
      fov: 45,
      contentAnchor: 'right',
      safeUiWidthPercent: 46,
      planetScreenPosition: 'left-center',
    },
  },
  {
    id: 'build',
    name: 'BUILD',
    subtitle: 'Engineered Systems & Projects',
    tagline: 'Full-Stack Architectures, Interactive Tools & Creative Software',
    orbitalRadius: 19,
    orbitalSpeed: 0.16,
    orbitalInclination: -0.12,
    size: 1.4,
    baseColor: '#334155',
    glowColor: '#f97316',
    atmosphereColor: '#ea580c',
    initialAngle: 2.1,
    position: [-16.2, -2.2, 9.4],
    composition: {
      cameraPositionOffset: [-2.8, 0.45, 4.2],
      lookAtOffset: [0.85, 0, 0],
      fov: 45,
      contentAnchor: 'right',
      safeUiWidthPercent: 46,
      planetScreenPosition: 'left-center',
    },
  },
  {
    id: 'music',
    name: 'MUSIC',
    subtitle: 'Acoustic Resonance & Taste',
    tagline: 'Curated Soundscapes, Harmonic Frequencies & Musical Identity',
    orbitalRadius: 27,
    orbitalSpeed: 0.11,
    orbitalInclination: 0.18,
    size: 1.25,
    baseColor: '#3b0764',
    glowColor: '#c084fc',
    atmosphereColor: '#9333ea',
    initialAngle: 3.8,
    position: [18.4, 4.8, -19.2],
    composition: {
      cameraPositionOffset: [-2.6, 0.4, 3.9],
      lookAtOffset: [0.8, 0, 0],
      fov: 45,
      contentAnchor: 'right',
      safeUiWidthPercent: 46,
      planetScreenPosition: 'left-center',
    },
  },
  {
    id: 'create',
    name: 'CREATE',
    subtitle: 'Polymath Dimensions',
    tagline: 'Instruments, Athletics, Fine Craft & Human Vitality',
    orbitalRadius: 35,
    orbitalSpeed: 0.08,
    orbitalInclination: -0.22,
    size: 1.35,
    baseColor: '#064e3b',
    glowColor: '#34d399',
    atmosphereColor: '#059669',
    initialAngle: 4.9,
    position: [-23.8, 6.4, -25.2],
    composition: {
      cameraPositionOffset: [-2.7, 0.45, 4.1],
      lookAtOffset: [0.85, 0, 0],
      fov: 45,
      contentAnchor: 'right',
      safeUiWidthPercent: 46,
      planetScreenPosition: 'left-center',
    },
  },
  {
    id: 'mindset',
    name: 'MINDSET',
    subtitle: 'Philosophy & Endurance',
    tagline: 'Quiet Intensity, Repetition, Resistance & The Unfinished Climb',
    orbitalRadius: 44,
    orbitalSpeed: 0.05,
    orbitalInclination: 0.14,
    size: 1.55,
    baseColor: '#020617',
    glowColor: '#fbbf24',
    atmosphereColor: '#d97706',
    initialAngle: 1.2,
    position: [32.1, -5.9, 29.5],
    composition: {
      cameraPositionOffset: [-3.2, 0.5, 4.6],
      lookAtOffset: [0.95, 0, 0],
      fov: 45,
      contentAnchor: 'right',
      safeUiWidthPercent: 46,
      planetScreenPosition: 'left-center',
    },
  },
];

export const UNIVERSE_VIEW_CAMERA: {
  position: [number, number, number];
  lookAt: [number, number, number];
} = {
  position: [0, 22, 38],
  lookAt: [0, 0, 0],
};

export const MULTIVERSE_START_CAMERA: {
  position: [number, number, number];
  lookAt: [number, number, number];
} = {
  position: [0, 180, 520],
  lookAt: [0, 0, 0],
};
